urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()
from content import views
from django.conf import settings
from django.conf.urls import patterns, url
from django.conf.urls.static import static
from django.conf.urls import *
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.index),
    url(r'^page/(.*)/$', views.pages),
    url(r'^contact/$', views.contact),


    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
) #+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
            }),
        url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
            }),
    )

content/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django import forms


class Pages(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название страницы')
    title = models.CharField(max_length=100, verbose_name='Заголовок страницы', help_text='TITLE', blank=True)
    slug = models.CharField(max_length=100, verbose_name='URL')
    text = models.TextField(verbose_name='Текст страницы')
    description = models.TextField(verbose_name='Описание страницы', blank=True, null=True, help_text='Не обязательно')

    class Meta:
        verbose_name = 'Страница'
        verbose_name_plural = 'страницы'

    def __unicode__(self):
        return self.name


class Navigation(models.Model):
    name = models.CharField(max_length=100, verbose_name='Название пункта')
    slug = models.CharField(max_length=100, verbose_name='URL')
    position = models.IntegerField(verbose_name=None, blank=True, null=True)

    class Meta:
        verbose_name = 'Навигация'
        verbose_name_plural = 'навигация'

    def __unicode__(self):
        return self.name


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField()
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

content/views.py
# -- coding: utf-8 --
#!/usr/bin/env python

from .models import Pages, Navigation, ContactForm
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt, requires_csrf_token, csrf_protect


def index(request):
    p = Pages.objects.get(slug='index')
    data = {'p': p}
    return render(request, 'index.html', data)


def pages(request, slug):
    p = Pages.objects.get(slug=slug)
    m = Navigation.objects.order_by('position')
    data = {'p': p, 'm': m}
    return render(request, 'pages.html', data)


def contact(request):
    if request.method == 'POST':  # If the form has been submitted...
        form = ContactForm(request.POST)  # A form bound to the POST data
        if form.is_valid():  # All validation rules pass
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']

            recipients = ['layzfromlp@gmail.com']
            if cc_myself:
                recipients.append(sender)

            from django.core.mail import send_mail
            send_mail(subject, message, sender, recipients)
        return HttpResponseRedirect('/page/thanks/')  # Redirect after POST
    else:
        form = ContactForm()  # An unbound form

    return render(request, 'contact.html', {
        'form': form,
    })



# https://docs.djangoproject.com/en/dev/howto/custom-template-tags/
# http://djbook.ru/rel1.4/howto/custom-template-tags.html

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %} {% endblock %} - ПсихоДом</title>
    <link href="{{ MEDIA_URL }}css/style.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="{{ MEDIA_URL }}core/js/jquery/jquery.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jScrollPane.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.mousewheel.min.js"></script>
    <script>
    $(function()
    {
    $('.scroll-pane').jScrollPane({showArrows:false,scrollbarWidth:18,dragMaxHeight:18});
    });
    </script>
    <!--[if IE 6]>
      <script src="js/fix.js" type="text/javascript"></script>
      <script type="text/javascript">
        DD_belatedPNG.fix('#phone');
        DD_belatedPNG.fix('#logo');
        DD_belatedPNG.fix('#logo span');
        DD_belatedPNG.fix('#question');
        DD_belatedPNG.fix('#question img');
        DD_belatedPNG.fix('#content');
        DD_belatedPNG.fix('#main_img');
        DD_belatedPNG.fix('.input');
        DD_belatedPNG.fix('.submit input');
        DD_belatedPNG.fix('.jScrollPaneTrack');
        DD_belatedPNG.fix('.jScrollPaneDrag');
      </script>
    <![endif]-->

<!-- Google Analytics -->
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-5505117-32', 'psihohome.com.ua');
  ga('send', 'pageview');

</script>
<!-- Google Analytics -->

</head>
<body>

{% block content %}
{% endblock %}
</body>
</html>

templates/contact.html
<form action="/contact/" method="post">{% csrf_token %}
{{ form.as_p }}
<input type="submit" value="Submit" />
</form>

templates/inc/question.html
<div id="question">
        <img src="{{ MEDIA_URL }}img/question.png" alt="Задать вопрос" />
        <script src="{{ MEDIA_URL }}core/Smarty-plugins/js/getBrowserInfo.js" type=text/javascript></script>
        <script language="javascript">getBrowserInfo();</script>
        <script src="{{ MEDIA_URL }}js/formFieldsCheck.js" type=text/javascript></script>

<!--
<form action="/contact/" method="post">{% csrf_token %}
<p><label for="id_subject">Subject:</label>
    <input id="id_subject" type="text" name="subject" maxlength="100" /></p>
<p><label for="id_message">Message:</label>
    <input type="text" name="message" id="id_message" /></p>
<p><label for="id_sender">Sender:</label>
    <input type="text" name="sender" id="id_sender" /></p>
<p><label for="id_cc_myself">Cc myself:</label>
    <input type="checkbox" name="cc_myself" id="id_cc_myself" /></p>
<input type="submit" value="Submit" />
</form>
-->

        <form action="/contact/" method="POST" onsubmit="javascript: return formFieldsCheck('form');" name="form"> {% csrf_token %}
            <div class="input">
                <input type="text" mandatoryfield="1" name="subject" id="id_subject" onclick="if (this.value == 'Ваше имя') this.value = '';" onblur="if (this.value == '') this.value = 'Ваше имя';" value="Ваше имя" />
            </div>
            <div class="input">
                <input type="text" mandatoryfield="1" preg_mask="/^[\.\-_A-Za-z0-9]+?@[\.\-A-Za-z0-9]+?\.[A-Za-z0-9]{2,6}$/" name="sender" id="id_sender" onclick="if (this.value == 'Ваш e-mail') this.value = '';" onblur="if (this.value == '') this.value = 'Ваш e-mail';" value="Ваш e-mail" />
            </div>

            <div class="input">
                <textarea name="message" id="id_message" mandatoryfield="1" onclick="if (this.value == 'Напишите Ваш вопрос') this.value = '';" onblur="if (this.value == '') this.value = 'Напишите Ваш вопрос';" >Напишите Ваш вопрос</textarea>
            </div>
            <div class="submit">
                <input type="submit" value="" />
            </div>
        </form>
</div>

<div>
<br>
</div>

templates/index.html
{% extends 'base.html' %}

{% block title %}{{ p.title|default:'Наши услуги' }}{% endblock %}
{% block content %}

<div id="top_menu">
    <div class="container">
    <ul>
    {% for menu in m %}
            <li><a href="/page/{{ menu.slug }}"> {{ menu.name }}</a></li>
    {% endfor %}
    </ul>
    </div>
</div>
<div id="bottom_menu">
    <div class="container"></div>
</div>


<div id="wrapper">
		<a id="logo" href="/"><span></span></a>
    {% include 'inc/question.html' %}
    <div id="content">
        <div id="sc-wrap">
            <div class="scroll-pane">
                <h1>{{ p.name }}</h1>
                <div class="text_page">
                    {{ p.text|safe }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/pages.html
{% extends 'base.html' %}

{% block title %}{{ p.title|default:'Наши услуги' }}{% endblock %}
{% block content %}

<div id="top_menu">
    <div class="container">
    <ul>
    {% for menu in m %}
            <li><a href="/page/{{ menu.slug }}"> {{ menu.name }}</a></li>
    {% endfor %}
    </ul>
    <span id="phone">+38 066 118 18 57</span>

    </div>
</div>

<div id="bottom_menu">
    <div class="container"></div>
</div>


<div id="wrapper">
		<a id="logo" href="/"><span></span></a>
    {% include 'inc/question.html' %}
    <div id="content">
        <div id="sc-wrap">
            <div class="scroll-pane">
                <h1>{{ p.name }}</h1>
                <div class="text_page">
                    {{ p.text|safe }}
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}